print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))
n= round(tip/100*bill+bill, 2)
print(f"Total tip for each person:  + ${n}")